### ISSUE TITLE
Incorrect version number used in Docker container

### ISSUE THREAD

**Issue by jetztgradnet** [AtomGraph/JSON2RDF#1]
When running JSON2RDF in the Docker container is shown in the readme, I get this error message:

```
xxxx [~/dev/workspaces/graphstuff/JSON2RDF]> echo "{'label':'Hello'}" | head -100 | docker run -i -a stdin -a stdout -a stderr atomgraph/json2rdf urn:test:
Error: Unable to access jarfile target/json2rdf-1.0.0-SNAPSHOT-jar-with-dependencies.jar
```

The version number in the Dockerfile wasn't adjusted when bumping the version to 1.0.1.

**Comment by namedgraph** [comment]
Good catch, thanks! Would be smart to automate this somehow, bet lets leave it for another time :)

**Comment by namedgraph** [comment]
The new image should auto-build shortly.
